import { useState } from 'react'
import { ArrowRight, Check, Eye, EyeOff, LockKeyhole } from 'lucide-react'

function AuthShell({ mode, children }) {
  const isSignIn = mode === 'sign-in'
  return <main className="auth-page"><header className="auth-header"><a className="auth-brand" href="/get-started"><span className="brand-mark"><i className="fa-regular fa-calendar-check" aria-hidden="true" /></span><span>Event<span>Flow</span></span></a><span>{isSignIn ? 'New to EventFlow?' : 'Already have an account?'}</span><a className="auth-header-link" href={isSignIn ? '/create-account' : '/sign-in'}>{isSignIn ? 'Create account' : 'Sign in'} <ArrowRight size={13} /></a></header><section className="auth-card-wrap"><div className="auth-card"><div className="auth-card-top"><span className="auth-eyebrow">{isSignIn ? 'Organizer access' : 'Start planning clearly'}</span><h1>{isSignIn ? 'Welcome back' : 'Create your account'}</h1><p>{isSignIn ? 'Sign in to continue managing your events.' : 'Build a calmer, more connected way to run events.'}</p></div>{children}</div><p className="auth-note"><LockKeyhole size={12} /> Your information is protected and never shared.</p></section><footer className="auth-footer">© 2026 EventFlow <span>·</span> Event planning &amp; management platform</footer></main>
}

export function SignIn() {
  const [showPassword, setShowPassword] = useState(false)
  return <AuthShell mode="sign-in"><form className="auth-form" onSubmit={(event) => event.preventDefault()}><label>Email address<input type="email" placeholder="you@example.com" autoComplete="email" required /></label><label><span className="label-row"><span>Password</span><a href="/sign-in">Forgot password?</a></span><span className="password-field"><input type={showPassword ? 'text' : 'password'} placeholder="Enter your password" autoComplete="current-password" required /><button type="button" aria-label={showPassword ? 'Hide password' : 'Show password'} onClick={() => setShowPassword((visible) => !visible)}>{showPassword ? <EyeOff size={15} /> : <Eye size={15} />}</button></span></label><label className="check-row"><input type="checkbox" /> <span>Keep me signed in</span></label><button className="auth-submit" type="submit">Sign in <ArrowRight size={15} /></button></form><div className="auth-divider"><span>or continue with</span></div><div className="provider-row"><button type="button"><span className="provider-google">G</span> Google</button><button type="button"><span className="provider-microsoft">▦</span> Microsoft</button></div><p className="auth-switch">Don't have an account? <a href="/create-account">Create one</a></p></AuthShell>
}

export function CreateAccount() {
  const [showPassword, setShowPassword] = useState(false)
  return <AuthShell mode="create-account"><form className="auth-form" onSubmit={(event) => event.preventDefault()}><div className="form-grid"><label>First name<input type="text" placeholder="Meyadur" autoComplete="given-name" required /></label><label>Last name<input type="text" placeholder="Rahman" autoComplete="family-name" required /></label></div><label>Email address<input type="email" placeholder="you@example.com" autoComplete="email" required /></label><label>Password<span className="password-field"><input type={showPassword ? 'text' : 'password'} placeholder="Create a password" autoComplete="new-password" required /><button type="button" aria-label={showPassword ? 'Hide password' : 'Show password'} onClick={() => setShowPassword((visible) => !visible)}>{showPassword ? <EyeOff size={15} /> : <Eye size={15} />}</button></span></label><div className="password-hint"><span><Check size={11} /> 8+ characters</span><span><Check size={11} /> One number</span><span><Check size={11} /> One symbol</span></div><label>Workspace name<input type="text" placeholder="e.g. Mayadur Events" /></label><label className="check-row terms-row"><input type="checkbox" required /> <span>I agree to the <a href="/create-account">Terms of Service</a> and <a href="/create-account">Privacy Policy</a>.</span></label><button className="auth-submit" type="submit">Create account <ArrowRight size={15} /></button></form><p className="auth-switch">Already have an account? <a href="/sign-in">Sign in</a></p></AuthShell>
}
