import { useState } from 'react'
import { ArrowRight, BriefcaseBusiness, Check, CheckCircle2, Eye, EyeOff, Grid2X2, LockKeyhole, ShieldCheck, UserRound, Users } from 'lucide-react'
import { saveDemoSession } from '../data/demoSession'

const accountRoles = {
  Organizer: { icon: UserRound, description: 'Create & manage events', email: 'name@eventflow.io', firstName: 'Meyadur', lastName: 'Rahman' },
  Staff: { icon: BriefcaseBusiness, description: 'View & update tasks', email: 'staff@eventflow.io', firstName: 'Tariqul', lastName: 'Islam' },
  Guest: { icon: Users, description: 'RSVP to invitations', email: 'guest@eventflow.io', firstName: 'Salman', lastName: 'Chowdhury' },
  Admin: { icon: ShieldCheck, description: 'Manage platform', email: 'admin@eventflow.com', firstName: 'Zayid', lastName: 'Karim' },
}

function AuthShell({ mode, children }) {
  const isSignIn = mode === 'sign-in'
  return <main className="auth-page"><header className="auth-header"><a className="auth-brand" href="/get-started"><span className="brand-mark"><i className="fa-regular fa-calendar-check" aria-hidden="true" /></span><span>Event<span>Flow</span></span></a><span>{isSignIn ? 'New to EventFlow?' : 'Already have an account?'}</span><a className="auth-header-link" href={isSignIn ? '/create-account' : '/sign-in'}>{isSignIn ? 'Create account' : 'Sign in'} <ArrowRight size={13} /></a></header><section className="auth-card-wrap"><div className="auth-card">{children}</div><p className="auth-note"><LockKeyhole size={12} /> Your information is protected and never shared.</p></section><footer className="auth-footer">© 2026 EventFlow <span>·</span> Event planning &amp; management platform</footer></main>
}

function AuthTabs({ active }) { return <div className="auth-tabs"><a className={active === 'sign-in' ? 'active' : ''} href="/sign-in">Sign In</a><a className={active === 'create-account' ? 'active' : ''} href="/create-account">Create Account</a></div> }

function RoleCards({ role, onRoleChange, includeAdmin = false }) {
  const roles = includeAdmin ? ['Organizer', 'Staff', 'Guest', 'Admin'] : ['Organizer', 'Staff', 'Guest']
  return <div className="role-card-picker"><div className="role-picker-heading"><span><Grid2X2 size={11} /> Select your account role <b>*</b></span>{!includeAdmin && <small>Role determines your workspace permissions</small>}</div><div className={`role-card-grid ${includeAdmin ? 'with-admin' : ''}`}>{roles.map((item) => { const roleInfo = accountRoles[item]; const Icon = roleInfo.icon; return <button type="button" key={item} className={`role-card-option ${role === item ? 'selected' : ''} ${item === 'Admin' ? 'admin' : ''}`} onClick={() => onRoleChange(item)}><span className="role-card-icon"><Icon size={13} /></span><strong>{item}</strong><small>{roleInfo.description}</small>{role === item && <CheckCircle2 className="role-card-check" size={11} />}</button> })}</div>{!includeAdmin && <small className="role-picker-note">Admin accounts are provisioned by the EventFlow team.</small>}</div>
}

export function SignIn() {
  const [showPassword, setShowPassword] = useState(false)
  const [role, setRole] = useState('Organizer')
  const handleSubmit = (event) => { event.preventDefault(); const sessionRole = role === 'Staff' || role === 'Guest' ? 'Organizer' : role; saveDemoSession(sessionRole); window.location.href = sessionRole === 'Admin' ? '/admin' : '/dashboard' }
  return <AuthShell mode="sign-in"><AuthTabs active="sign-in" /><div className="auth-card-top auth-reference-heading"><span className="auth-eyebrow">{role} access</span><h1>Welcome Back</h1><p>Sign in to coordinate venues, vendors, guests, schedules, and operations.</p></div><div className="auth-success"><CheckCircle2 size={13} /><span>You have been safely signed out. Please sign in below to access your workspace.</span><button aria-label="Dismiss">×</button></div><RoleCards role={role} onRoleChange={setRole} includeAdmin /><p className="role-context">Signing in as <strong>{role}</strong></p><form className="auth-form" onSubmit={handleSubmit}><label><span className="auth-label">Work Email Address <b>*</b></span><span className="input-with-icon"><UserRound size={13} /><input type="email" placeholder={accountRoles[role].email} autoComplete="email" required /></span></label><label><span className="label-row"><span>Password <b>*</b></span><a href="/sign-in">Forgot password?</a></span><span className="password-field input-with-icon"><LockKeyhole size={13} /><input type={showPassword ? 'text' : 'password'} placeholder="••••••••••" autoComplete="current-password" required /><button type="button" aria-label={showPassword ? 'Hide password' : 'Show password'} onClick={() => setShowPassword((visible) => !visible)}>{showPassword ? <EyeOff size={14} /> : <Eye size={14} />}</button></span></label><div className="auth-meta"><label className="check-row"><input type="checkbox" defaultChecked /> <span>Remember me for 30 days</span></label><small>SSL 256-bit Encrypted</small></div><button className="auth-submit" type="submit">Sign in to EventFlow <ArrowRight size={14} /></button></form><div className="auth-divider"><span>or continue with</span></div><div className="provider-row"><button type="button"><span className="provider-google">G</span> Continue with Google</button></div><p className="auth-switch">Don't have an EventFlow account? <a href="/create-account">Create an account</a></p></AuthShell>
}

export function CreateAccount() {
  const [showPassword, setShowPassword] = useState(false)
  const [showConfirmPassword, setShowConfirmPassword] = useState(false)
  const [role, setRole] = useState('Organizer')
  const handleSubmit = (event) => { event.preventDefault(); const inputs = event.currentTarget.querySelectorAll('input[type="text"]'); const nameParts = (inputs[0]?.value || `${accountRoles[role].firstName} ${accountRoles[role].lastName}`).trim().split(/\s+/); const firstName = nameParts.shift() || accountRoles[role].firstName; const lastName = nameParts.join(' ') || accountRoles[role].lastName; const sessionRole = role === 'Staff' || role === 'Guest' ? 'Organizer' : role; saveDemoSession(sessionRole, { firstName, lastName, initials: `${firstName[0]}${lastName[0]}`.toUpperCase() }); window.location.href = sessionRole === 'Admin' ? '/admin' : '/dashboard' }
  return <AuthShell mode="create-account"><AuthTabs active="create-account" /><div className="auth-card-top auth-reference-heading"><h1>Create Your Account</h1><p>Join EventFlow to plan, coordinate, or participate in unified events.</p></div><RoleCards role={role} onRoleChange={setRole} /><p className="role-context">{role} permissions will be applied to your new account.</p><form className="auth-form" onSubmit={handleSubmit}><div className="form-grid"><label>Full Name <b>*</b><input type="text" placeholder={`${accountRoles[role].firstName} ${accountRoles[role].lastName}`} autoComplete="name" required /></label><label>Work Email Address <b>*</b><input type="email" placeholder={accountRoles[role].email} autoComplete="email" required /></label></div><label>Organization / Agency Name <small className="optional-label">(Optional)</small><input type="text" placeholder="e.g. Apex Events Ltd." /></label><label>Password <b>*</b><span className="password-field input-with-icon"><LockKeyhole size={13} /><input type={showPassword ? 'text' : 'password'} placeholder="At least 8 characters" autoComplete="new-password" required /><button type="button" aria-label={showPassword ? 'Hide password' : 'Show password'} onClick={() => setShowPassword((visible) => !visible)}>{showPassword ? <EyeOff size={14} /> : <Eye size={14} />}</button></span></label><label>Confirm Password <b>*</b><span className="password-field input-with-icon"><LockKeyhole size={13} /><input type={showConfirmPassword ? 'text' : 'password'} placeholder="Repeat password" autoComplete="new-password" required /><button type="button" aria-label={showConfirmPassword ? 'Hide password' : 'Show password'} onClick={() => setShowConfirmPassword((visible) => !visible)}>{showConfirmPassword ? <EyeOff size={14} /> : <Eye size={14} />}</button></span></label><label className="check-row terms-row"><input type="checkbox" required /> <span>I agree to the <a href="/create-account">Terms of Service</a> and <a href="/create-account">Privacy Policy</a>.</span></label><button className="auth-submit" type="submit">Create Account &amp; Get Started <ArrowRight size={14} /></button></form><p className="auth-switch">Already have an EventFlow account? <a href="/sign-in">Sign in</a></p></AuthShell>
}
