import { ArrowRight, BarChart3, CalendarDays, Check, CheckCircle2, ChevronRight, ClipboardCheck, Clock3, LayoutDashboard, Mail, Menu, ShieldCheck, Users, WalletCards } from 'lucide-react'

const capabilities = [
  ['Event Management', ['Create and manage events', 'Track event statuses, dates, venue, and budget'], CalendarDays],
  ['Venue Booking', ['Browse and manage event venues', 'Store capacity and booking information'], LayoutDashboard],
  ['Vendor Management', ['Assign vendors to events', 'Track vendor details and booking status'], WalletCards],
  ['Guest & RSVP', ['Manage invitations', 'Track accepted, declined, and pending guests'], Users],
  ['Task Management', ['Assign tasks to staff', 'Track pending, in-progress, and completed tasks'], ClipboardCheck],
  ['Event Schedule', ['Create event agendas', 'Manage start times, end times, and notes'], Clock3],
]
const workflow = [['1', 'Create your event', 'Input details, set dates, and give your event a clear home.'], ['2', 'Plan & execute', 'Manage tasks, vendors, guests, and communications from one dashboard.'], ['3', 'Track progress', 'Monitor check-ins, planning milestones, and engagement in real time.']]

function WorkspacePreview() {
  return <div className="workspace-preview"><div className="workspace-browser-bar"><span><i /><i /><i /></span><b>EventFlow Workspace · Active Dashboard</b><em>Live Operations</em></div><div className="workspace-summary"><div><small>FEATURED EVENT <b>ID: #EVF-2026-08</b></small><h3>Global Tech Innovators Summit 2026</h3><p>October 24–26, 2026 <span>•</span> Grand Horizon Convention Center (Hall A)</p></div><dl><div><dt>Allocated budget</dt><dd>$65,000</dd></div><div><dt>Target attendees</dt><dd>450 people</dd></div><div className="health"><dt>Plan health</dt><dd>92% Ready</dd></div></dl></div><div className="workspace-columns"><div className="workspace-card upcoming-card"><header><strong>Upcoming events</strong><small>3 scheduled</small></header><article><b>AI &amp; Robotics Executive Dinner</b><span>Nov 12 · 8:00 PM</span><em>Confirmed</em></article><article><b>Annual Healthcare Symposium</b><span>Dec 05 · 9:00 AM</span><em className="planning">Planning</em></article></div><div className="workspace-card tasks-card"><header><strong>Coordination tasks</strong><em>18/24 Completed</em></header><p><CheckCircle2 size={12} /> Audio &amp; Visual Rigging <small>Staff: Tariq</small></p><p><span className="task-dot" /> VIP Catering Delegation <small className="progress-text">In Progress</small></p></div><div className="workspace-card guests-card"><header><strong>Guest RSVP status</strong><small>450 invited</small></header><div className="rsvp-bar"><i /><i /><i /></div><div className="rsvp-counts"><span><b>304</b>Accepted</span><span><b>64</b>Pending</span><span><b>32</b>Declined</span></div></div></div><div className="workspace-columns bottom"><div className="workspace-card schedule-card"><header><strong>Live event schedule · day 1 run of show</strong><small>3 of 5 sessions</small></header><div className="schedule-items"><article><b>09:00 – 10:30 AM</b><strong>Opening Keynote</strong><small>Grand Hall · Dr. Elena Vance</small></article><article><b>11:00 – 12:30 PM</b><strong>Technical Breakouts</strong><small>Rooms 101–104 · 4 Tracks</small></article><article><b>01:00 – 02:30 PM</b><strong>Networking Lunch</strong><small>Terrace Pavilion · Live Chef</small></article></div></div><div className="workspace-card vendors-card"><header><strong>Venues &amp; vendors</strong><em>All Confirmed</em></header><p><span>Grand Horizon Hall</span><small>Venue · Capacity 500</small><b>Booked</b></p><p><span>Audio/Video Media AV</span><small>Audio/Visual Partner</small><b>Contracted</b></p></div></div></div>
}

function Capabilities() {
  return <section className="marketing-section capabilities-section" id="features"><div className="marketing-section-head"><span>Modular Core Capabilities</span><h2>Everything You Need to Manage Your<br /><em>Event</em></h2><p>From venue selection to real-time day-of execution, EventFlow coordinates each milestone inside one unified system.</p></div><div className="capability-grid">{capabilities.map(([title, bullets, Icon]) => <article key={title}><div className="capability-icon"><Icon size={17} /></div><span className="capability-dot" /><h3>{title}</h3><ul>{bullets.map((bullet) => <li key={bullet}><Check size={10} /> {bullet}</li>)}</ul><footer><small>Structured Flow</small><ChevronRight size={11} /></footer></article>)}</div></section>
}

export default function LandingPage() {
  return <main className="marketing-page"><header className="marketing-header"><a className="marketing-brand" href="/"><span className="brand-mark"><i className="fa-regular fa-calendar-check" aria-hidden="true" /></span><span><b>Event<span>Flow</span></b><small>MANAGEMENT SYSTEM</small></span></a><nav><a href="#features">Features</a><a href="#workflow">How It Works</a><a href="#about">About</a></nav><div className="marketing-actions"><a href="/sign-in">Sign In</a><a className="marketing-workspace" href="/create-account"><LayoutDashboard size={13} /> Open Workspace</a></div><button className="marketing-menu" aria-label="Open menu"><Menu size={17} /></button></header><section className="marketing-hero"><div className="marketing-kicker"><span /> Event management <span /></div><h1>Plan Every Event.<br /><em>One Flow.</em></h1><p>Streamline your event planning with EventFlow. From concept to post-event analysis, manage everything in one powerful platform.</p><div className="marketing-hero-actions"><a className="marketing-dark-button" href="/create-account">Get Started <ArrowRight size={15} /></a><a className="marketing-light-button" href="#features">Learn More</a></div><WorkspacePreview /></section><Capabilities /><section className="marketing-section workflow-v2" id="workflow"><div className="marketing-section-head"><span>Workflow</span><h2>How EventFlow<br /><em>works.</em></h2></div><div className="workflow-grid-v2">{workflow.map(([number, title, description]) => <article key={number}><div>{number}</div><h3>{title}</h3><p>{description}</p></article>)}</div></section><section className="marketing-cta" id="about"><span>Ready to get started?</span><h2>Make event planning easier.</h2><p>Join event teams using EventFlow to create clearer, more connected experiences.</p><div><a className="marketing-light-button" href="/create-account">Get Started Now</a><a className="marketing-outline-button" href="/sign-in">Sign In</a></div></section><footer className="marketing-footer"><a className="marketing-brand" href="/"><span className="brand-mark"><i className="fa-regular fa-calendar-check" aria-hidden="true" /></span><span><b>Event<span>Flow</span></b><small>MANAGEMENT SYSTEM</small></span></a><p>The all-in-one event management platform for confident teams.</p><div><a href="#features"><Mail size={14} /></a><a href="#features"><ShieldCheck size={14} /></a><a href="#features"><BarChart3 size={14} /></a></div><small>© 2026 EventFlow. All rights reserved.</small></footer></main>
}
